cache:
  - duration: none
final_space: true
patch_pwsh_bleed: true
shell_integration: true
version: 3
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: path
        style: powerline
        powerline_symbol: ""
        foreground: "#ffffff"
        background: "#0077be"
        properties:
          style: folder
      - type: git
        style: powerline
        powerline_symbol: ""
        foreground: "#ffffff"
        background: "#28a745"
        properties:
          display_status: true
          display_stash_count: true
